#!/usr/bin/env node
/**
 * Claude WordPress Bridge — MCP connector.
 *
 * Wraps the "Claude Admin Bridge" WordPress plugin so Claude can administer a
 * site over the REST API. Authentication uses the token you generated in the
 * plugin; it is sent as a Bearer header on every request.
 *
 * Required environment variables:
 *   WP_BRIDGE_URL    Base REST URL, e.g. https://example.com/wp-json/
 *   WP_BRIDGE_TOKEN  The token generated by the plugin (cab_...)
 *
 * Optional:
 *   WP_BRIDGE_READONLY  If "true", blocks any non-GET request as a safety rail.
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const BASE_URL = (process.env.WP_BRIDGE_URL || "").replace(/\/+$/, "");
const TOKEN = process.env.WP_BRIDGE_TOKEN || "";
const READONLY = String(process.env.WP_BRIDGE_READONLY || "").toLowerCase() === "true";

if (!BASE_URL || !TOKEN) {
  console.error(
    "[claude-wordpress-bridge] Missing WP_BRIDGE_URL or WP_BRIDGE_TOKEN environment variables."
  );
  process.exit(1);
}

const BRIDGE_NS = "claude-bridge/v1";

/**
 * Perform a request against the WordPress REST API.
 *
 * @param {string} method  HTTP method.
 * @param {string} path    REST path relative to the base, e.g. "wp/v2/posts".
 * @param {object} [opts]  { query, body }.
 */
async function wpFetch(method, path, opts = {}) {
  const upper = method.toUpperCase();
  if (READONLY && upper !== "GET") {
    throw new Error(
      `Blocked: WP_BRIDGE_READONLY is enabled, so ${upper} requests are not allowed.`
    );
  }

  const clean = String(path).replace(/^\/+/, "");
  const url = new URL(`${BASE_URL}/${clean}`);
  if (opts.query && typeof opts.query === "object") {
    for (const [k, v] of Object.entries(opts.query)) {
      if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
    }
  }

  const headers = {
    Authorization: `Bearer ${TOKEN}`,
    Accept: "application/json",
  };
  let payload;
  if (opts.body !== undefined && upper !== "GET" && upper !== "HEAD") {
    headers["Content-Type"] = "application/json";
    payload = typeof opts.body === "string" ? opts.body : JSON.stringify(opts.body);
  }

  const res = await fetch(url, { method: upper, headers, body: payload });
  const text = await res.text();
  let data;
  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    data = text;
  }

  return { status: res.status, ok: res.ok, data };
}

function result(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    isError: !payload.ok && payload.ok !== undefined ? false : false,
  };
}

const TOOLS = [
  {
    name: "wp_status",
    description:
      "Verify the connection and show which site and admin user the bridge is acting as.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "wp_request",
    description:
      "Generic authenticated call to the WordPress REST API. Use this for almost anything an admin can do: posts, pages, media, users, comments, categories, tags, settings. " +
      'Path is relative to the REST base, e.g. "wp/v2/posts" or "wp/v2/users". ' +
      "Examples: list posts (GET wp/v2/posts), create a post (POST wp/v2/posts with body {title, content, status}), " +
      "update a user (POST wp/v2/users/5 with body {...}), delete a post (DELETE wp/v2/posts/12?force=true).",
    inputSchema: {
      type: "object",
      properties: {
        method: {
          type: "string",
          enum: ["GET", "POST", "PUT", "PATCH", "DELETE"],
          description: "HTTP method.",
        },
        path: {
          type: "string",
          description: 'REST path relative to the base, e.g. "wp/v2/posts".',
        },
        query: {
          type: "object",
          description: "Optional query-string parameters.",
          additionalProperties: true,
        },
        body: {
          type: "object",
          description: "Optional JSON body for write requests.",
          additionalProperties: true,
        },
      },
      required: ["method", "path"],
      additionalProperties: false,
    },
  },
  {
    name: "wp_list_plugins",
    description: "List installed plugins and whether each is active.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "wp_toggle_plugin",
    description: "Activate or deactivate a plugin by its file path (e.g. akismet/akismet.php).",
    inputSchema: {
      type: "object",
      properties: {
        plugin: { type: "string", description: "Plugin file path." },
        action: { type: "string", enum: ["activate", "deactivate"] },
      },
      required: ["plugin", "action"],
      additionalProperties: false,
    },
  },
  {
    name: "wp_list_themes",
    description: "List installed themes and which one is active.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "wp_activate_theme",
    description: "Activate a theme by its stylesheet directory name.",
    inputSchema: {
      type: "object",
      properties: { stylesheet: { type: "string" } },
      required: ["stylesheet"],
      additionalProperties: false,
    },
  },
  {
    name: "wp_get_option",
    description: "Read a WordPress option value by name (protected secrets are blocked).",
    inputSchema: {
      type: "object",
      properties: { name: { type: "string" } },
      required: ["name"],
      additionalProperties: false,
    },
  },
  {
    name: "wp_set_option",
    description: "Write a WordPress option value by name (protected secrets are blocked).",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string" },
        value: { description: "Any JSON-serialisable value." },
      },
      required: ["name", "value"],
      additionalProperties: false,
    },
  },
  {
    name: "wp_site_health",
    description: "Return an environment/health snapshot of the site.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "wp_audit_log",
    description: "Return recent bridge activity recorded on the site.",
    inputSchema: {
      type: "object",
      properties: { limit: { type: "number" } },
      additionalProperties: false,
    },
  },
];

const server = new Server(
  { name: "claude-wordpress-bridge", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args = {} } = request.params;

  try {
    switch (name) {
      case "wp_status":
        return result(await wpFetch("GET", `${BRIDGE_NS}/status`));

      case "wp_request":
        return result(
          await wpFetch(args.method, args.path, { query: args.query, body: args.body })
        );

      case "wp_list_plugins":
        return result(await wpFetch("GET", `${BRIDGE_NS}/plugins`));

      case "wp_toggle_plugin":
        return result(
          await wpFetch("POST", `${BRIDGE_NS}/plugins/${args.action}`, {
            body: { plugin: args.plugin },
          })
        );

      case "wp_list_themes":
        return result(await wpFetch("GET", `${BRIDGE_NS}/themes`));

      case "wp_activate_theme":
        return result(
          await wpFetch("POST", `${BRIDGE_NS}/themes/activate`, {
            body: { stylesheet: args.stylesheet },
          })
        );

      case "wp_get_option":
        return result(await wpFetch("GET", `${BRIDGE_NS}/options/${encodeURIComponent(args.name)}`));

      case "wp_set_option":
        return result(
          await wpFetch("POST", `${BRIDGE_NS}/options/${encodeURIComponent(args.name)}`, {
            body: { value: args.value },
          })
        );

      case "wp_site_health":
        return result(await wpFetch("GET", `${BRIDGE_NS}/site-health`));

      case "wp_audit_log":
        return result(
          await wpFetch("GET", `${BRIDGE_NS}/audit-log`, {
            query: args.limit ? { limit: args.limit } : undefined,
          })
        );

      default:
        return {
          content: [{ type: "text", text: `Unknown tool: ${name}` }],
          isError: true,
        };
    }
  } catch (err) {
    return {
      content: [{ type: "text", text: `Error: ${err.message}` }],
      isError: true,
    };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
console.error("[claude-wordpress-bridge] MCP server ready.");
